<a href="https://colab.research.google.com/github/hiid0726/DataAnalysis/blob/main/hiid0726/ch05_01_numpy_%EA%B8%B0%EC%B4%88_ym.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 배열(Array)
* 많은 데이터를 하나의 변수에 넣는 법? : **리스트**
* 하지만 리스트는...
    * 속도가 느리다
    * 메모리를 많이 차지한다

> 그래서? **배열(Array)**을 사용한다

* 적은 메모리로 많은 데이터를 빠르게 처리할 수 있음

## 특징
1. 모든 원소가 같은 **자료형**이어야 함
2. 원소의 갯수를 바꿀 수 없음

> 그런데 파이썬은 자체적으로 배열 자료형을 제공하지 않음<br>
> 그래서 우리는 **넘파이(Numpy)** 패키지를 import해서 사용 

In [2]:
import numpy as np;

## 1차원 배열
* 리스트나 튜플처럼 한 줄로 이루어진 형태의 배열

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
arr = np.array(range(10))
arr, type(arr) # numpy.ndarray

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

## ndarray
* 배열 객체 타입(자료형)
* 리스트와 동일해 보이지만 차이가 많음

|자료형|특징|
|:-|:-|
|리스트(list)|각각의 원소가 다른 자료형이 될 수 있음|
|배열(array)|연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 함<br>원소에 대한 접근과 반복문 실행이 빨라짐|

In [7]:
import random;


def average_python(n):
# n개의 랜덤한 0~1의 실수를 평균해주는 함수
  s=0;
  for i in range(n) :
    s += random.random()
  return s/n;

In [9]:
%time average_python(100000)

CPU times: user 17.2 ms, sys: 0 ns, total: 17.2 ms
Wall time: 19 ms


0.4989320688672243

In [10]:
%timeit average_python(10)

1.76 µs ± 517 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [11]:
def average_numpy(n):
  # n개의 랜덤한 0~1의 실수를 numpy를 사용해서 평균내는 함수
  s = np.random.random(n) # numpy에 있는 random 함수
  return s.mean() #.mean() = 평균

In [12]:
%time average_numpy(10)

CPU times: user 775 µs, sys: 0 ns, total: 775 µs
Wall time: 719 µs


0.37619572025475556

In [13]:
%timeit average_numpy(10)

10.4 µs ± 2.11 µs per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## 벡터화 연산
* 배열 객체는 **배열의 각 원소에 대한 반복 연산을 하나의 명령어로 처리**하는 벡터화 연산(vectorized operation)을 지원

In [14]:
data = list(range(10))
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [15]:
# 여러 개의 데이터를 모두 2배 할 때 (파이썬)
%%time
answer = []
for v in data :
  answer.append(v * 2)

answer ## 요소요소에 *2 하기

CPU times: user 16 µs, sys: 1e+03 ns, total: 17 µs
Wall time: 21.5 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
# 리스트 컴프리헨션
%%time
[v * 2 for v in data]

CPU times: user 7 µs, sys: 0 ns, total: 7 µs
Wall time: 12.4 µs


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [17]:
# 리스트 컴프리헨션
%%timeit
[v * 2 for v in data]

1.01 µs ± 302 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [18]:
# 벡터화 연산
arr = np.array(data)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# 리스트 객체에 정수를 곱하면 객체의 크기가 해당 정수 배만큼 증가


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

* 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용

(array([1, 2, 3]), array([10, 20, 30]))

array([12, 24, 36])

(array([False,  True, False]), array([False,  True,  True]))

(array([False,  True, False]), array([False,  True,  True]))

## 2차원 배열
* `ndarray`는 N-dimensional Array의 약자, 즉 1차원 배열 이외에도 2차원 배열, 3차원 배열 등의 다차원 배열 자료 구조를 지원
* 2차원 배열 = 행렬 (matrix)
* 가로줄 : 행(row), 세로줄 : 열(column)
> 엑셀 스프레드시트와 같은 형태의 배열

* 리스트의 리스트(list of list)를 이용하여 2차원 배열 생성
    * 안쪽 리스트의 길이 : 행렬의 열의 수 (가로 크기)
    * 바깥쪽 리스트의 길이 : 행렬의 행의 수 (세로 크기)

In [26]:
arr = np.array([[0,1,2], [3,4,5]])
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
# 행의 갯수, 열의 갯수
len(arr), len(arr[0])

(2, 3)

## 💡 연습문제 1
> 아래 모양의 행렬 만들어 보기
```
10 20 30 40
50 60 70 80
```

In [32]:
arr = np.array([[10,20,30,40], [50,60,70,80]])
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [47]:
arr = np.array([[1,2,3,4], [5,6,7,8]]) * 10 ## 연산
arr

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [38]:
np.arange(10, 90, 10).reshape(2,-1)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

## 3차원 배열

In [51]:
# 크기를 나타낼 때는 가장 바깥쪽 리스트의 길이부터 가장 안쪽 리스트 길이의 순서로 표시
t = np.array([
                [
                    [1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]
                 ]
                ,[
                    [11,12,13,14],
                    [15,16,17,18],
                    [19,20,21,22]
                  ]
                ])
t # 2x3x4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [52]:
# 깊이, 행, 열
len(t), len(t[0]), len(t[0][0])

(2, 3, 4)

## 배열의 차원과 크기 알아내기
* `ndim`, `shape` **속성** 사용
> 속성 : 괄호 없이 이름만 써서 값을 호출

* `ndim` : 배열의 차원
* `shape` : 배열의 크기

In [53]:
a = np.array(range(1,4))
a

array([1, 2, 3])

In [56]:
a.ndim, a.shape

(1, (3,))

In [58]:
m = np.array((range(3),range(3,6)))
m

array([[0, 1, 2],
       [3, 4, 5]])

In [60]:
m.ndim, m.shape # 2x3 (행, 열)

(2, (2, 3))

In [61]:
t.ndim, t.shape # 2x3x4 (깊이, 행, 열)

(3, (2, 3, 4))

## 배열의 복사
* copy와 view의 차이점은 copy는 새 배열(깊은 복사)이고 view는 원래 배열과 연결 되어 있다는 것(얕은 복사)
* copy는 데이터를 소유하며 copy에 대한 변경 사항은 원본 배열에 영향을 미치지 않으며 원본 배열에 대한 변경은 copy에 영향을 주지 않음
* view는 데이터를 소유하지 않으며 view에 대한 모든 변경 사항은 원래 배열에 영향을 미치고 원래 배열에 대한 모든 변경 사항은 보기에 영향을 줌

In [63]:
import numpy as np;

arr = np.array(range(1,6))
x = arr.copy()
arr[0] = 5 ## arr만 바뀐다. 연결 안됨. (깊은 복사)
print(arr)
print(x)

[5 2 3 4 5]
[1 2 3 4 5]


In [65]:
arr = np.array(range(1,6))
x = arr.view()   ###### 연결되는 것!! (얕은 복사)
arr[0] = 5 ## x도 같이 바뀐다!!! (얕은 복사)
x[1] = 10
print(arr)
print(x)

[ 5 10  3  4  5]
[ 5 10  3  4  5]


In [66]:
arr = np.array(range(1,6))
x = arr.view(float)   ###### veiw는 주로 형변환이 필요할때 사용한다 ^^ 거의 안씀!
arr[0] = 5 ## x도 같이 바뀐다!!! (얕은 복사)
x[1] = 10
print(arr)
print(x)

[                  5 4621819117588971520                   3
                   4                   5]
[2.5e-323 1.0e+001 1.5e-323 2.0e-323 2.5e-323]


In [67]:
import numpy as np;

arr = np.array(range(1,6))

x = arr.copy()
y = arr.view()

##### 배열 데이터 소유 여부 반환 --> 혹시나 헷갈릴때... 그냥 복사할때는 무조건 copy쓰는게 안전 ^-^!!
print(x.base)
print(y.base)

None
[1 2 3 4 5]


## 배열의 인덱싱

### 일차원 배열
* 리스트의 인덱싱과 같음

In [74]:
a = np.array(range(5))
print(a)
a[2], a[-1]

[0 1 2 3 4]


(2, 4)

### 다차원 배열
* 콤마(comma, `,`)를 사용하여 접근
* 콤마로 구분된 차원을 축(axis)라고 함
    * like 그래프의 x축, y축

In [77]:
b = np.array([
    [0,1,2], [3,4,5]
])
print(b)

[[0 1 2]
 [3 4 5]]


In [78]:
b[0,0] ## [행,열]

0

In [79]:
b[0,1]

1

In [81]:
b[-1,-1]

5

## 배열 슬라이싱
* 다차원 배열의 원소 중 2개 이상의 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함께 사용

In [82]:
a = np.array([
    [0,1,2,3], [4,5,6,7]
])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
a[0,:] # 첫번째 행의 전체 열

array([0, 1, 2, 3])

In [84]:
a[:,1] # 두번째 열의 전체 행

array([1, 5])

In [85]:
a[1,1:] # 두번째 행의 두번째 열부터 끝 열까지

array([5, 6, 7])

In [87]:
a[:2,:2] # 첫번째행부터 두번째 행까지, 첫번째 열부터 두번째 열까지.

array([[0, 1],
       [4, 5]])

In [90]:
a[:,2:] # 세번째 열부터 마지막 열까지.

array([[2, 3],
       [6, 7]])

## 💡 연습문제 2

In [91]:
m = np.array([[0,  1,  2,  3,  4],
              [5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [95]:
#@markdown (1) 값 7을 인덱싱
m[1,2], m[1,-3], m[-2,2], m[-2,-3]

(7, 7, 7, 7)

In [96]:
#@markdown (2) 값 14을 인덱싱
m[2,4],m[2,-1], m[-1,4],  m[-1,-1]

(14, 14, 14, 14)

In [101]:
#@markdown (3) 배열 [6,7]을 슬라이싱
m[1,1:3], m[-2,1:3], m[1,-4:-2],m[-2,-4:-2]

(array([6, 7]), array([6, 7]), array([6, 7]), array([6, 7]))

In [104]:
#@markdown (4) 배열 [7,12]을 슬라이싱
m[1:,2], m[-2:,2], m[1:,-3], m[-2:, -3]

(array([ 7, 12]), array([ 7, 12]), array([ 7, 12]), array([ 7, 12]))

In [108]:
#@markdown (5) 배열 [[3,4],[8,9]]을 슬라이싱
print(m[:2,3:])
print(m[:-1,3:])
print(m[:2,-2:])
print(m[:-1,-2:])

[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]
[[3 4]
 [8 9]]


## 배열 인덱싱
* 대괄호(Bracket, [])안의 인덱스 정보로 숫자나 슬라이스가 아니라 위치 정보를 나타내는 또다른 `ndarray` 배열을 받을 수 있음 (인덱스 배열)
* 일종의 조건 검색 기능

### 불리언 (Boolean) 배열 인덱싱
* 인덱스 배열의 원소가 True, False 두 값으로만 구성되며 인덱스 배열의 크기가 원래 ndarray 객체의 크기와 같아야 함

In [111]:
# 0~8 사이의 (끝포함) 짝수만 가진 배열
a1 = np.array(range(0,9,2))
a2 = np.array([i for i in range(9) if not (i % 2)])
a1, a2

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [113]:
# 짝수인 원소만 골라내고 싶다면?
# 짝수에 대응하는 곳에 True, 홀수에 대응하는 곳에 False
a = np.array(range(10))
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
idx = np.array([True,False,True,False,True,False,True,False,True,False])
idx

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [116]:
a[idx] #-> idx에서 True인 값만 추출

array([0, 2, 4, 6, 8])

In [117]:
# 조건문 연산
a % 2 #벡터화 연산

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [118]:
a%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [119]:
a[a%2==0]

array([0, 2, 4, 6, 8])

### 정수 배열 인덱싱
* 인덱스 배열의 원소 각각이 원래 `ndarray` 객체 원소 하나를 가리키는 인덱스 정수이여야 함

In [121]:
a = np.array(range(1,10))*11
a

array([11, 22, 33, 44, 55, 66, 77, 88, 99])

In [122]:
idx = np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

* 이 때는 배열 인덱스의 크기가 원래의 배열 크기와 달라도 상관없음
* 같은 원소를 반복해서 가리키는 경우에는 배열 인덱스가 원래의 배열보다 더 커지기도 함

In [123]:
idx = np.array([0]*6 + [1]*5 + [2]*5)
a[idx]

array([11, 11, 11, 11, 11, 11, 22, 22, 22, 22, 22, 33, 33, 33, 33, 33])

### 다차원 배열에서의 배열 인덱싱

In [127]:
a = np.array([
    range(1,5),
    range(5,9),
    range(9,13)
])
a, a.ndim, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), 2, (3, 4))

In [128]:
print(a[:,[0,3]])
print(a[:,[0,-1]])
print(a[:,(True, False, False, True)])

[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]
[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [130]:
print(a[[2, 0, 1],:])

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


## 💡 연습문제 3

In [132]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [141]:
# (1) 3의 배수 찾기
x[x%3 == 0], x[x%3 != 0]

(array([ 3,  6,  9, 12, 15, 18]),
 array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14, 16, 17, 19, 20]))

In [142]:
# (2) 4로 나누면 1이 남는 수 찾기
x[x%4 == 1], x[x//4 == 1]

(array([ 1,  5,  9, 13, 17]), array([4, 5, 6, 7]))

In [146]:
# (3) 3로 나누면 나누어지고 4로 나누면 1이 남는 수 찾기
x[(x%3==0) & (x%4 == 1)],x[(x%3==0) | (x%4 == 1)] ## and , or

(array([9]), array([ 1,  3,  5,  6,  9, 12, 13, 15, 17, 18]))

## 배열 검색

In [147]:
arr = np.array([1,2,3,4,5,4,4])
arr

array([1, 2, 3, 4, 5, 4, 4])

In [149]:
# np.where(배열 비교/논리 연산) -> 조건을 만족시킨 값의 인덱스를 반환한다.
x = np.where(arr==4) ## 해당 값의 인덱스를 리턴한다.
y = np.where(arr%2 == 0) ## 해당 값의 인덱스를 리턴!
x, y

((array([3, 5, 6]),), (array([1, 3, 5, 6]),))

In [151]:
arr = np.array(range(1,9))
x= np.where(arr%2 == 0)

arr[x], arr[arr%2 == 0] # 같은 결과 ^--^

(array([2, 4, 6, 8]), array([2, 4, 6, 8]))