<a href="https://colab.research.google.com/github/andy9806/DataAnalysis_23/blob/main/andy9806/0308.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
a={
    'a':{
        'ab':1234,
         'awee':4321
    },
   'b':232,
   'c':231
}

In [6]:
a.items()

dict_items([('a', {'ab': 1234, 'awee': 4321}), ('b', 232), ('c', 231)])

In [7]:
for i in enumerate(a.items(),1):
  print(i)

(1, ('a', {'ab': 1234, 'awee': 4321}))
(2, ('b', 232))
(3, ('c', 231))


In [15]:
class MeatError(Exception):
  def __init__(self,msg):
    super().__init__(msg)
    # self.msg = msg

try:
  raise MeatError('오류발생')
except MeatError as e :
  print(e)

오류발생


In [16]:
!pip install yfinance -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 KB 5.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 KB 6.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 53.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.2/112.2 KB 11.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.2/111.2 KB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 KB 13.7 MB/s eta 0:00:00


In [20]:
from datetime import datetime

In [23]:
import yfinance as yf
df = yf.Ticker('TSLA').history(start ='2023-02-25',end = datetime.now())
df

Open        High         Low       Close  \
Date                                                                        
2023-02-27 00:00:00-05:00  202.029999  209.419998  201.259995  207.630005   
2023-02-28 00:00:00-05:00  210.589996  211.229996  203.750000  205.710007   
2023-03-01 00:00:00-05:00  206.210007  207.199997  198.520004  202.770004   
2023-03-02 00:00:00-05:00  186.740005  193.750000  186.009995  190.899994   
2023-03-03 00:00:00-05:00  194.800003  200.479996  192.880005  197.789993   
2023-03-06 00:00:00-05:00  198.539993  198.600006  192.300003  193.809998   
2023-03-07 00:00:00-05:00  191.380005  194.199997  186.100006  187.710007   

                              Volume  Dividends  Stock Splits  
Date                                                           
2023-02-27 00:00:00-05:00  161028300        0.0           0.0  
2023-02-28 00:00:00-05:00  153144900        0.0           0.0  
2023-03-01 00:00:00-05:00  156852800        0.0           0.0  
2023-03-02 00:00:00-05:00  181500700        0.0           0.0  
2023-03-03 00:00:00-05:00  153800400        0.0           0.0  
2023-03-06 00:00:00-05:00  127800600        0.0           0.0  
2023-03-07 00:00:00-05:00  148125790        0.0           0.0

In [25]:
import numpy as np

In [28]:
a=[i for i in range(10)]
np.array(a)
arr = np.array(range(10))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
import random

def aver(n):
  s=0
  for i in range(n):
    s+=random.random()
  return s/n

In [42]:
%time aver(100000)

CPU times: user 16.8 ms, sys: 0 ns, total: 16.8 ms
Wall time: 22.1 ms


0.49727364601225804

In [43]:
%timeit aver(100000)

14.6 ms ± 3.95 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [44]:
def avera(n):
  s = np.random.random(n)
  return s.mean()

In [45]:
%time avera(100000)

CPU times: user 2.46 ms, sys: 0 ns, total: 2.46 ms
Wall time: 2.25 ms


0.4984735059387282

In [46]:
%timeit avera(100000)

1.28 ms ± 393 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [64]:
np.random.randint(5)

0

In [66]:
np.random.randn(2)

array([-0.3612555, -0.3477348])

In [ ]:
np.random.random(10)              #0과1 사이의 값 10개
np.random.uniform(-5,5,10)        #-5에서 5 사이의 값 10개
np.linspace(-5,5,11)              #-5에서 5 사이의 간격을 동일하게 11개
# np.random.seed(5)               난수를 5seed로 고정하여 나타냄. 난수생성시 계속해서 같은 값을 반환함
np.random.randint(-3,15,3)        #-3에서 14까지 랜덤으로 3개 반환 but 중복허용
np.random.randint(6)              #0부터 5까지 하나 반환
# np.random.randint(1,[3,5,10])   ??
np.random.rand(3,2)               #0과1사이의 값을 3,2로 반환
# np.random.random(3,2)           #error occurs because random.random은 1개의 파라미터만 받음, 매트릭스로 반환 X
np.random.rand(10)                #np.random.random(10)과 동일한듯?? 이러면 random.rand만 기억해도 될 듯
np.random.normal(10,2,10)         #평균이 10이고 분산이 2인 값 10개
np.random.normal(10,2,size=(3,2)) #개수 자리에 size로 매트릭스로 반환 가능
np.random.randn(3,2)              #평균이0 분산이1인 정규분포의 값을 3,2 로 반환
np.random.randn(5)                #평균이0 분산이1인 정규분포의 값을 5개 반환 np.random.normal(0,1,5)와 동일

In [68]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
np.array([[10,20,30,40],[50,60,70,80]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [72]:
np.array([[1,2,3,4],[5,6,7,8]])*10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [85]:
b=np.arange(10,90,10).reshape(2,4)

In [80]:
a=np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],
          [[4,3,2,1],
          [8,7,6,5],
          [12,11,10,9]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]]])

In [82]:
a.shape

(2, 3, 4)

In [83]:
a.ndim

3

In [86]:
b[:,:]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [87]:
b[0,0]

10

In [88]:
b[-1,-1]

80

In [89]:
b[:,2:]

array([[30, 40],
       [70, 80]])

In [92]:
b[0:1,:]

array([[10, 20, 30, 40]])

In [94]:
b[1:2,2:]

array([[70, 80]])

In [95]:
a[:,:,:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]]])

In [96]:
a[0:1,:,:]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [98]:
c=np.arange(0,10,2)
c

array([0, 2, 4, 6, 8])

In [100]:
d=np.array(range(10))
d[d%2==0]

array([0, 2, 4, 6, 8])

In [101]:
a=np.array(range(1,10))*11
idx= np.array([0,2,4,6,8])
a[idx]

array([11, 33, 55, 77, 99])

In [102]:
idx=np.array([0]*5+[2]*2+[1]*3)
a[idx]

array([11, 11, 11, 11, 11, 33, 33, 22, 22, 22])

In [152]:
a=np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],
          [[4,3,2,1],
          [8,7,6,5],
          [12,11,10,9]]])

In [156]:
a[0,:,[1,3]]

array([[ 2,  6, 10],
       [ 4,  8, 12]])

In [110]:
x=np.array(range(1,21))

In [112]:
x[x%3==0]

array([ 3,  6,  9, 12, 15, 18])

In [113]:
x[x%4==1]

array([ 1,  5,  9, 13, 17])

In [115]:
x[(x%3==0) & (x%4==1)]

array([9])

In [118]:
arr = np.array([12,3,4,55,44,2,3,4,44,4,4,4,2,3,3,4])
arr

array([12,  3,  4, 55, 44,  2,  3,  4, 44,  4,  4,  4,  2,  3,  3,  4])

In [120]:
g=np.where(arr==4)  #arr==4인 인덱스를 반환

In [121]:
arr[g]

array([4, 4, 4, 4, 4, 4])

In [122]:
x=np.array(range(10))
x.dtype

dtype('int64')

In [124]:
x=np.array([1,2,3.0])
x.dtype

dtype('float64')

In [126]:
x=np.array([1,2,3],dtype='f')
x

array([1., 2., 3.], dtype=float32)

In [127]:
x=np.array([1,2,3],dtype=float)
x

array([1., 2., 3.])

In [130]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [133]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [135]:
d=np.zeros(5,dtype='U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [136]:
d[0]='abc'
d[1]='abcd'
d[2]='abcde'
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [139]:
f=np.ones((2,3,4,5))
f

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [140]:
np.zeros_like(f,dtype=int)

array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]])

In [146]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [147]:
np.logspace(0.1,1,10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [158]:
a=np.array([1,2,3,4])
a[1:3]
a[[1,3]]

array([2, 4])

In [160]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [161]:
a[np.newaxis,:]

array([[1, 2, 3, 4]])